Basic functionalities implementation
membraneframework/membrane_opentelemetry pull request #1
Opened 2022-06-06 17:15 UTC by FelonEkonom

2022-06-23 06:09 UTC, daniel-jodlos commented on README.md
> +This repository contains Membrane wrappers on OpenTelemetry functions.
Being a little more verbose wouldn't hurt. After reading this, I still don't really know what I'm looking at

```suggestion
This repository contains Membrane wrappers of OpenTelemetry functions.
```

2022-06-23 06:09 UTC, daniel-jodlos commented on README.md
> +Copyright 2020, [Software Mansion](https://swmansion.com/?utm_source=git&utm_medium=readme&utm_campaign=membrane_opentelemetry)
```suggestion
Copyright 2022, [Software Mansion](https://swmansion.com/?utm_source=git&utm_medium=readme&utm_campaign=membrane_opentelemetry)
```

2022-06-23 06:09 UTC, daniel-jodlos commented on lib/opentelemetry.ex
> +  Provided macros evalueate to appropriate calls to OpenTelemetry functions or to nothing, depending on config values
```suggestion
  Provided macros expand to appropriate calls to OpenTelemetry functions or to nothing, depending on config values
```

2022-06-23 06:09 UTC, daniel-jodlos commented on lib/opentelemetry.ex
> +      else: default_macro([name, opts])
do you need to call this? Why not just...
```suggestion
```

Also, `default_macro` is a little strange. It's effectively "no operation", right? So maybe let's call it `no_action` or something like that

2022-06-23 10:24 UTC, mat-hek requested changes

2022-06-23 10:24 UTC, mat-hek commented on lib/opentelemetry.ex
> +  defmacro register() do
```suggestion
  defmacro register_process() do
```

2022-06-23 10:24 UTC, mat-hek commented on lib/opentelemetry.ex
> +  Starts a new span. If the second argument contains value `parent` under key `:parent`, then span named `parent` will be the parent span of the newly created one.
```suggestion
  Starts a new span. 
  
  Options:
  - `parent` - a span that will be the parent of the created span
```

2022-06-23 10:24 UTC, mat-hek commented on lib/opentelemetry.ex
> +  Defines macros for operations on OpenTelemetry spans.
Add better description and usage example

2022-06-23 10:24 UTC, mat-hek commented on lib/opentelemetry.ex
> +      OpenTelemetry.Tracer.set_current_span(new_span)
Don't alter `current span` whenever possible

2022-06-23 15:26 UTC, mickel8 approved these changes

2022-06-23 15:26 UTC, mickel8 commented on .github/workflows/fetch_changes.yml
>        # Runs a set of commands using the runners shell
This file should be deleted

2022-06-23 15:26 UTC, mickel8 commented on lib/opentelemetry.ex
> +      else: default_macro([name, opts])
If `default_macro` is needed, maybe `void` would be a siutable name?

2022-06-27 09:05 UTC, mat-hek requested changes

2022-06-27 09:05 UTC, mat-hek commented on README.md
> +Membrane.OpenTelemetry.start_span("root_span")
I'd mention that "root_span" is the span ID and it has to be unique and what it's for

2022-06-27 09:05 UTC, mat-hek commented on README.md
> +config :membrane_opentelemetry, enabled: telemetry_enabled
```suggestion
config :membrane_opentelemetry, enabled: true
```

2022-06-27 09:05 UTC, mat-hek commented on README.md
> +```
````suggestion
To get the span context, call 
```elixir
root_span_ctx = Membrane.OpenTelemetry.get_span("root_span") 
```
in the process that started the `root_span`.
````

2022-06-27 09:05 UTC, mat-hek commented on README.md
> +Membrane.OpenTelemetry.register_process()
As discussed, let's do that automatically when starting the first span

2022-06-27 09:05 UTC, mat-hek commented on README.md
> +```
Describe what's the name and how it differs from the id

2022-06-27 09:05 UTC, mat-hek commented on lib/opentelemetry.ex
> +  """
Write what it returns

2022-06-28 09:14 UTC, mat-hek approved these changes

2022-06-28 14:26 UTC, merged